---
from: <%= ENV['APPLICATION_EMAIL_FROM'] %>
domain: <%= ENV['APPLICATION_DOMAIN_NAME'] %>
strategy: sendmail
smtp_settings:
  address:
  port:
  domain:
  user_name:
  password:
  authentication:
  enable_starttls_auto:
