---
development:
  adapter: postgresql
  encoding: utf8
  database: squash_development
test:
  adapter: postgresql
  encoding: utf8
  database: squash_test
production:
  adapter: postgresql
  encoding: utf8
  username: app
  database: rails_production
  pool: 30
